language: c
sudo: false
compiler:
  - gcc
  - clang

os:
  - linux
  - osx

branches:
  only:
    - staging
    - trying
    - master

before_script:
    - if [ "$TRAVIS_OS_NAME" == "osx" ] ; then brew update; brew install redis; fi

addons:
  apt:
    packages:
    - libc6-dbg
    - libc6-dev
    - libc6:i386
    - libc6-dev-i386
    - libc6-dbg:i386
    - gcc-multilib
    - g++-multilib
    - valgrind
    - libevent-dev
    - libev-dev
    - libuv-dev
    - libivykis-dev
    - libqt4-dev

env:
    - BITS="32"
    - BITS="64"

script:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      EXAMPLES="macosx";
      if [ "$BITS" == "32" ]; then
        CONF_FLAGS="--host=i686-apple-darwin11";
        CFLAGS="-m32 -Werror";
        LDFLAGS="-m32";
      else
        CFLAGS="-Werror";
      fi;
    else
      CHECK_EXTRA="-valgrind";
      if [ "$BITS" == "32" ]; then
        CONF_FLAGS="--host=i686-linux-gnu";
        CFLAGS="-m32 -Werror";
        LDFLAGS="-m32";
      else
        EXAMPLES="libevent,libev,libuv,ivykis,qt";
        CFLAGS="-Werror";
      fi;
    fi;
    export CONF_FLAGS CFLAGS LDFLAGS CHECK_EXTRA EXAMPLES
  - autoreconf -i
  - mkdir build/ && cd build/
  - ../configure $CONF_FLAGS --enable-examples=$EXAMPLES
  - make
  - make check$CHECK_EXTRA || (grep . test-suite*.log && exit 1)
